# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}
      - name: SAM Deploy
        uses: falnyr/aws-sam-deploy-action@v1.0.0
        env:
          TEMPLATE: 'cloudformation/template.yaml'
          AWS_STACK_NAME: portal
          AWS_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
          PARAMETER_OVERRIDES: DevPortalSiteS3BucketName=${{ secrets.AWS_DEV_PORTAL_BUCKET }} CognitoDomainNameOrPrefix=${{ secrets.COGNITO_PREFIX }} ArtifactsS3BucketName=${{ secrets.ARTIFACTS_BUCKET }} CustomDomainName=${secrets.CUSTOM_DOMAIN_NAME} StaticAssetRebuildToken=${{ steps.buildnumber.outputs.build_number }} CustomDomainNameAcmCertArn=${secrets.CERT_ARN} UseRoute53Nameservers="false"
